# Generated by Django 5.2 on 2025-07-02 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_material_shifting_received_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('about', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('subscribed_date', models.DateField(blank=True, null=True)),
                ('subscribed_till', models.DateField(blank=True, null=True)),
                ('subscribed_prise', models.IntegerField(blank=True, null=True)),
                ('uu_id', models.CharField(blank=True, max_length=255, null=True)),
                ('t_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gst', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=55)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=155)),
                ('bank_account_bank_name', models.CharField(blank=True, default='', max_length=155)),
                ('bank_account_branch_name', models.CharField(blank=True, default='', max_length=155)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=55)),
                ('upi_id', models.CharField(blank=True, default='', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_limit', models.IntegerField()),
                ('project_limit', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='material_shifting_received',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Goa', 'Goa'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Jharkhand', 'Jharkhand'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Bihar', 'Bihar'), ('TamilNadu', 'TamilNadu'), ('Chhattisgarh', 'Chhattisgarh'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Nagaland', 'Nagaland'), ('Kerala', 'Kerala'), ('Chandigarh', 'Chandigarh'), ('Telangana', 'Telangana'), ('Gujarat', 'Gujarat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Meghalaya', 'Meghalaya'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Sikkim', 'Sikkim'), ('Ladakh', 'Ladakh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Puducherry', 'Puducherry'), ('Maharashtra', 'Maharashtra'), ('Uttarakhand', 'Uttarakhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Manipur', 'Manipur'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('West Bengal', 'West Bengal'), ('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Karnataka', 'Karnataka'), ('Assam', 'Assam'), ('Madhya Pradesh', 'Madhya Pradesh')], default='', max_length=155),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('subscribed_date', models.DateField(blank=True, null=True)),
                ('subscribed_till', models.DateField(blank=True, null=True)),
                ('subscribed_prise', models.IntegerField(blank=True, null=True)),
                ('uu_id', models.CharField(blank=True, max_length=255, null=True)),
                ('t_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subscriptionplan'),
        ),
    ]
