# Generated by Django 5.2 on 2025-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_company_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Odisha', 'Odisha'), ('Bihar', 'Bihar'), ('Meghalaya', 'Meghalaya'), ('Haryana', 'Haryana'), ('Maharashtra', 'Maharashtra'), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujarat', 'Gujarat'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('Kerala', 'Kerala'), ('Tripura', 'Tripura'), ('Goa', 'Goa'), ('Nagaland', 'Nagaland'), ('TamilNadu', 'TamilNadu'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal'), ('Telangana', 'Telangana'), ('Delhi', 'Delhi'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Mizoram', 'Mizoram'), ('Karnataka', 'Karnataka'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Punjab', 'Punjab'), ('Ladakh', 'Ladakh'), ('Sikkim', 'Sikkim')], default='', max_length=155),
        ),
    ]
