# Generated by Django 5.2 on 2025-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_company_user_limit_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Others', 'Others'), ('Male', 'Male')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Puducherry', 'Puducherry'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Rajasthan', 'Rajasthan'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Manipur', 'Manipur'), ('Lakshadweep', 'Lakshadweep'), ('Gujarat', 'Gujarat'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Ladakh', 'Ladakh'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Bihar', 'Bihar'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Sikkim', 'Sikkim'), ('Punjab', 'Punjab'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Maharashtra', 'Maharashtra'), ('TamilNadu', 'TamilNadu'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Kerala', 'Kerala'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Meghalaya', 'Meghalaya')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_yearly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
