# Generated by Django 5.2 on 2025-07-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_subscriptionplan_description_subscriptionplan_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='total_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Rajasthan', 'Rajasthan'), ('Uttarakhand', 'Uttarakhand'), ('Mizoram', 'Mizoram'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Gujarat', 'Gujarat'), ('Sikkim', 'Sikkim'), ('Lakshadweep', 'Lakshadweep'), ('Chhattisgarh', 'Chhattisgarh'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('TamilNadu', 'TamilNadu'), ('Assam', 'Assam'), ('Telangana', 'Telangana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Kerala', 'Kerala'), ('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Meghalaya', 'Meghalaya'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Puducherry', 'Puducherry'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Bihar', 'Bihar'), ('Manipur', 'Manipur'), ('Goa', 'Goa'), ('Ladakh', 'Ladakh'), ('Jharkhand', 'Jharkhand'), ('Haryana', 'Haryana'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Tripura', 'Tripura'), ('Karnataka', 'Karnataka')], default='', max_length=155),
        ),
    ]
