# Generated by Django 5.2 on 2025-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_subscriptionplan_total_months_alter_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Jharkhand', 'Jharkhand'), ('Uttarakhand', 'Uttarakhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Puducherry', 'Puducherry'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Mizoram', 'Mizoram'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Manipur', 'Manipur'), ('West Bengal', 'West Bengal'), ('Telangana', 'Telangana'), ('Haryana', 'Haryana'), ('Nagaland', 'Nagaland'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Karnataka', 'Karnataka'), ('Odisha', 'Odisha'), ('TamilNadu', 'TamilNadu'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Gujarat', 'Gujarat'), ('Ladakh', 'Ladakh'), ('Bihar', 'Bihar'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Lakshadweep', 'Lakshadweep'), ('Tripura', 'Tripura'), ('Meghalaya', 'Meghalaya'), ('Sikkim', 'Sikkim'), ('Punjab', 'Punjab')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='total_months',
            field=models.IntegerField(default=0),
        ),
    ]
