# Generated by Django 5.2 on 2025-07-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_subscriptionplan_total_amount_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='SubscriptionPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Tripura', 'Tripura'), ('Karnataka', 'Karnataka'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Lakshadweep', 'Lakshadweep'), ('Chandigarh', 'Chandigarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Sikkim', 'Sikkim'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Kerala', 'Kerala'), ('Gujarat', 'Gujarat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Delhi', 'Delhi'), ('TamilNadu', 'TamilNadu'), ('West Bengal', 'West Bengal'), ('Ladakh', 'Ladakh'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Rajasthan', 'Rajasthan'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Telangana', 'Telangana'), ('Goa', 'Goa'), ('Mizoram', 'Mizoram'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry')], default='', max_length=155),
        ),
    ]
