# Generated by Django 5.2 on 2025-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_payment_subscriptionplan_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Jharkhand', 'Jharkhand'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Puducherry', 'Puducherry'), ('Nagaland', 'Nagaland'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Odisha', 'Odisha'), ('Sikkim', 'Sikkim'), ('Haryana', 'Haryana'), ('Ladakh', 'Ladakh'), ('Mizoram', 'Mizoram'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Meghalaya', 'Meghalaya'), ('Gujarat', 'Gujarat'), ('Lakshadweep', 'Lakshadweep'), ('Karnataka', 'Karnataka'), ('Tripura', 'Tripura'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Manipur', 'Manipur'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('TamilNadu', 'TamilNadu'), ('West Bengal', 'West Bengal'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Andhra Pradesh', 'Andhra Pradesh')], default='', max_length=155),
        ),
    ]
