# Generated by Django 5.2 on 2025-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_company_email_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Mizoram', 'Mizoram'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Haryana', 'Haryana'), ('Sikkim', 'Sikkim'), ('Nagaland', 'Nagaland'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Meghalaya', 'Meghalaya'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('West Bengal', 'West Bengal'), ('Lakshadweep', 'Lakshadweep'), ('Ladakh', 'Ladakh'), ('Kerala', 'Kerala'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Puducherry', 'Puducherry'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Telangana', 'Telangana'), ('Gujarat', 'Gujarat'), ('Odisha', 'Odisha'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Uttarakhand', 'Uttarakhand'), ('Tripura', 'Tripura'), ('Goa', 'Goa'), ('TamilNadu', 'TamilNadu'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Karnataka', 'Karnataka'), ('Chandigarh', 'Chandigarh')], default='', max_length=155),
        ),
    ]
