# Generated by Django 5.2 on 2025-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Others', 'Others'), ('Male', 'Male')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('Mizoram', 'Mizoram'), ('Maharashtra', 'Maharashtra'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujarat', 'Gujarat'), ('Ladakh', 'Ladakh'), ('Bihar', 'Bihar'), ('Uttarakhand', 'Uttarakhand'), ('Lakshadweep', 'Lakshadweep'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Kerala', 'Kerala'), ('Jharkhand', 'Jharkhand'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Odisha', 'Odisha'), ('Telangana', 'Telangana'), ('Meghalaya', 'Meghalaya'), ('TamilNadu', 'TamilNadu'), ('Punjab', 'Punjab'), ('Madhya Pradesh', 'Madhya Pradesh'), ('West Bengal', 'West Bengal'), ('Chhattisgarh', 'Chhattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Nagaland', 'Nagaland'), ('Puducherry', 'Puducherry'), ('Goa', 'Goa'), ('Tripura', 'Tripura'), ('Assam', 'Assam'), ('Rajasthan', 'Rajasthan'), ('Manipur', 'Manipur'), ('Sikkim', 'Sikkim'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Delhi', 'Delhi')], default='', max_length=155),
        ),
    ]
