# Generated by Django 5.2 on 2025-07-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_company_email_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Assam', 'Assam'), ('Rajasthan', 'Rajasthan'), ('Puducherry', 'Puducherry'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Odisha', 'Odisha'), ('TamilNadu', 'TamilNadu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra'), ('Sikkim', 'Sikkim'), ('Karnataka', 'Karnataka'), ('Lakshadweep', 'Lakshadweep'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Ladakh', 'Ladakh'), ('Tripura', 'Tripura'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Uttarakhand', 'Uttarakhand'), ('Gujarat', 'Gujarat'), ('West Bengal', 'West Bengal'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Punjab', 'Punjab')], default='', max_length=155),
        ),
    ]
