# Generated by Django 5.2 on 2025-07-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_company_subscription_plan_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='inventory_use',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='material_shifting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='material_shifting_received',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='project_daily_work_details',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='project_investor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='project_plan_files',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='project_pre_plan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='project_work_inspection_details',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='stocks_in_inventory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Odisha', 'Odisha'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Lakshadweep', 'Lakshadweep'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Puducherry', 'Puducherry'), ('Gujarat', 'Gujarat'), ('Bihar', 'Bihar'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Sikkim', 'Sikkim'), ('Nagaland', 'Nagaland'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('TamilNadu', 'TamilNadu'), ('Ladakh', 'Ladakh'), ('Kerala', 'Kerala'), ('Delhi', 'Delhi'), ('Telangana', 'Telangana'), ('Mizoram', 'Mizoram'), ('Uttarakhand', 'Uttarakhand'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Chhattisgarh', 'Chhattisgarh'), ('Punjab', 'Punjab'), ('Meghalaya', 'Meghalaya'), ('Rajasthan', 'Rajasthan'), ('Himachal Pradesh', 'Himachal Pradesh'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tripura', 'Tripura')], default='', max_length=155),
        ),
    ]
