# Generated by Django 5.2 on 2025-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_attendance_company_inventory_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Mizoram', 'Mizoram'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Maharashtra', 'Maharashtra'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('West Bengal', 'West Bengal'), ('Lakshadweep', 'Lakshadweep'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Chhattisgarh', 'Chhattisgarh'), ('Gujarat', 'Gujarat'), ('Odisha', 'Odisha'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Sikkim', 'Sikkim'), ('Nagaland', 'Nagaland'), ('Punjab', 'Punjab'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Kerala', 'Kerala'), ('Rajasthan', 'Rajasthan'), ('Puducherry', 'Puducherry'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Tripura', 'Tripura'), ('Chandigarh', 'Chandigarh'), ('Meghalaya', 'Meghalaya'), ('Delhi', 'Delhi'), ('Jharkhand', 'Jharkhand'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('TamilNadu', 'TamilNadu'), ('Telangana', 'Telangana'), ('Haryana', 'Haryana')], default='', max_length=155),
        ),
    ]
