# Generated by Django 5.2 on 2025-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_project_photo_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_shifting_received',
            name='company',
        ),
        migrations.RemoveField(
            model_name='material_shifting_received',
            name='project',
        ),
        migrations.RemoveField(
            model_name='material_shifting_received',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Manipur', 'Manipur'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Odisha', 'Odisha'), ('Delhi', 'Delhi'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Ladakh', 'Ladakh'), ('Sikkim', 'Sikkim'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Goa', 'Goa'), ('Puducherry', 'Puducherry'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Telangana', 'Telangana'), ('Jharkhand', 'Jharkhand'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Chandigarh', 'Chandigarh'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Meghalaya', 'Meghalaya'), ('Karnataka', 'Karnataka'), ('Rajasthan', 'Rajasthan'), ('Kerala', 'Kerala'), ('Uttarakhand', 'Uttarakhand'), ('Mizoram', 'Mizoram'), ('Lakshadweep', 'Lakshadweep'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Punjab', 'Punjab'), ('TamilNadu', 'TamilNadu'), ('Gujarat', 'Gujarat')], default='', max_length=155),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Material_shifting_received',
        ),
    ]
