# Generated by Django 5.2 on 2025-07-18 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_material_shifting_received_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pwd_sr_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_deadline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_estimate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_estimate_file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_plan_file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Assam', 'Assam'), ('Ladakh', 'Ladakh'), ('Mizoram', 'Mizoram'), ('Haryana', 'Haryana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Puducherry', 'Puducherry'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Uttarakhand', 'Uttarakhand'), ('Tripura', 'Tripura'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('TamilNadu', 'TamilNadu'), ('West Bengal', 'West Bengal'), ('Chandigarh', 'Chandigarh'), ('Nagaland', 'Nagaland'), ('Maharashtra', 'Maharashtra'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Sikkim', 'Sikkim'), ('Chhattisgarh', 'Chhattisgarh'), ('Punjab', 'Punjab'), ('Karnataka', 'Karnataka'), ('Odisha', 'Odisha'), ('Goa', 'Goa'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Rajasthan', 'Rajasthan'), ('Lakshadweep', 'Lakshadweep'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Telangana', 'Telangana'), ('Meghalaya', 'Meghalaya'), ('Delhi', 'Delhi')], default='', max_length=155),
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='project/')),
                ('details', models.TextField(blank=True, default='')),
                ('cost', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, default='', max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='project/')),
                ('total_hours', models.CharField(blank=True, default='', max_length=55)),
                ('total_cost', models.CharField(blank=True, default='', max_length=55)),
                ('start_time', models.TimeField(blank=True)),
                ('break_start_time', models.TimeField(blank=True)),
                ('break_end_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_images', models.ImageField(blank=True, upload_to='project/')),
                ('Machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='project_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='project/')),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qc_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='project/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('no_days', models.CharField(blank=True, default='', max_length=25)),
                ('per_day_salary', models.CharField(blank=True, default='', max_length=25)),
                ('total_salary', models.CharField(blank=True, default='', max_length=55)),
                ('photo', models.ImageField(blank=True, upload_to='profile/')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
    ]
