# Generated by Django 5.2 on 2025-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_pwd_sr_rates_project_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_progress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Tripura', 'Tripura'), ('Mizoram', 'Mizoram'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Odisha', 'Odisha'), ('Sikkim', 'Sikkim'), ('Manipur', 'Manipur'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Puducherry', 'Puducherry'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chandigarh', 'Chandigarh'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Punjab', 'Punjab'), ('Delhi', 'Delhi'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Nagaland', 'Nagaland'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('West Bengal', 'West Bengal'), ('Meghalaya', 'Meghalaya'), ('Lakshadweep', 'Lakshadweep'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Rajasthan', 'Rajasthan'), ('TamilNadu', 'TamilNadu'), ('Chhattisgarh', 'Chhattisgarh')], default='', max_length=155),
        ),
    ]
