# Generated by Django 5.2 on 2025-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_project_progress_date_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_reports',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Gujarat', 'Gujarat'), ('Jharkhand', 'Jharkhand'), ('Rajasthan', 'Rajasthan'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Goa', 'Goa'), ('Telangana', 'Telangana'), ('Bihar', 'Bihar'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Assam', 'Assam'), ('Kerala', 'Kerala'), ('Delhi', 'Delhi'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Mizoram', 'Mizoram'), ('West Bengal', 'West Bengal'), ('Manipur', 'Manipur'), ('Sikkim', 'Sikkim'), ('TamilNadu', 'TamilNadu'), ('Odisha', 'Odisha'), ('Uttarakhand', 'Uttarakhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Tripura', 'Tripura'), ('Lakshadweep', 'Lakshadweep'), ('Nagaland', 'Nagaland'), ('Punjab', 'Punjab'), ('Maharashtra', 'Maharashtra'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Ladakh', 'Ladakh'), ('Puducherry', 'Puducherry'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Meghalaya', 'Meghalaya'), ('Chandigarh', 'Chandigarh')], default='', max_length=155),
        ),
    ]
