# Generated by Django 5.2 on 2025-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_qc_reports_date_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Odisha', 'Odisha'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Chandigarh', 'Chandigarh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Sikkim', 'Sikkim'), ('Jharkhand', 'Jharkhand'), ('Rajasthan', 'Rajasthan'), ('West Bengal', 'West Bengal'), ('Punjab', 'Punjab'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Assam', 'Assam'), ('Ladakh', 'Ladakh'), ('Puducherry', 'Puducherry'), ('TamilNadu', 'TamilNadu'), ('Nagaland', 'Nagaland'), ('Uttarakhand', 'Uttarakhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Mizoram', 'Mizoram'), ('Meghalaya', 'Meghalaya'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Lakshadweep', 'Lakshadweep'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'), ('Telangana', 'Telangana'), ('Manipur', 'Manipur'), ('Tripura', 'Tripura'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh')], default='', max_length=155),
        ),
    ]
