# Generated by Django 5.2 on 2025-07-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_expenses_date_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='machinery',
            name='bill',
            field=models.ImageField(blank=True, upload_to='project/'),
        ),
        migrations.AddField(
            model_name='machinery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujarat', 'Gujarat'), ('Chandigarh', 'Chandigarh'), ('Lakshadweep', 'Lakshadweep'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Uttarakhand', 'Uttarakhand'), ('Meghalaya', 'Meghalaya'), ('Sikkim', 'Sikkim'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Manipur', 'Manipur'), ('Odisha', 'Odisha'), ('TamilNadu', 'TamilNadu'), ('Bihar', 'Bihar'), ('Ladakh', 'Ladakh'), ('Punjab', 'Punjab'), ('Chhattisgarh', 'Chhattisgarh'), ('Tripura', 'Tripura'), ('Telangana', 'Telangana'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Maharashtra', 'Maharashtra'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Kerala', 'Kerala'), ('Nagaland', 'Nagaland'), ('Puducherry', 'Puducherry'), ('Rajasthan', 'Rajasthan'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Karnataka', 'Karnataka'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Mizoram', 'Mizoram'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh')], default='', max_length=155),
        ),
    ]
