# Generated by Django 5.2 on 2025-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_machinery_added_date_machinery_bill_machinery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Puducherry', 'Puducherry'), ('Chhattisgarh', 'Chhattisgarh'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Punjab', 'Punjab'), ('Kerala', 'Kerala'), ('TamilNadu', 'TamilNadu'), ('Odisha', 'Odisha'), ('Nagaland', 'Nagaland'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Ladakh', 'Ladakh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jharkhand', 'Jharkhand'), ('Maharashtra', 'Maharashtra'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Uttarakhand', 'Uttarakhand'), ('Mizoram', 'Mizoram'), ('Telangana', 'Telangana'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Tripura', 'Tripura'), ('Chandigarh', 'Chandigarh'), ('Sikkim', 'Sikkim'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Lakshadweep', 'Lakshadweep'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir')], default='', max_length=155),
        ),
    ]
