# Generated by Django 5.2 on 2025-07-24 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_salary_added_date_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_shifting',
            name='image_re',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='material_shifting',
            name='lat_re',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='material_shifting',
            name='lon_re',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='material_shifting',
            name='user_re',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material_shifting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Karnataka', 'Karnataka'), ('Mizoram', 'Mizoram'), ('Dadra & Nagar Haveli & Daman & Diu', 'Dadra & Nagar Haveli & Daman & Diu'), ('Maharashtra', 'Maharashtra'), ('Nagaland', 'Nagaland'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Gujarat', 'Gujarat'), ('Meghalaya', 'Meghalaya'), ('Chandigarh', 'Chandigarh'), ('Goa', 'Goa'), ('Manipur', 'Manipur'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Lakshadweep', 'Lakshadweep'), ('Chhattisgarh', 'Chhattisgarh'), ('Jharkhand', 'Jharkhand'), ('Kerala', 'Kerala'), ('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tripura', 'Tripura'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Sikkim', 'Sikkim'), ('Bihar', 'Bihar'), ('Puducherry', 'Puducherry'), ('Assam', 'Assam'), ('Odisha', 'Odisha'), ('Ladakh', 'Ladakh'), ('TamilNadu', 'TamilNadu'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi')], default='', max_length=155),
        ),
    ]
